services:

  database:
    ports: !reset []

  backend:
    build: !reset null
    image: ghcr.io/quentinverscheure/zelda-cv-backend:latest
    pull_policy: always
    ports: !reset []

  frontend:
    build: !reset null
    image: ghcr.io/quentinverscheure/zelda-cv-frontend:latest
    pull_policy: always
    ports: !override
      - "127.0.0.1:8082:80"