spring.application.name=Zelda-cv
spring.datasource.url=jdbc:mysql://localhost:3306/zeldacv
spring.datasource.username=root
spring.datasource.password=pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=off
app.jwt-secret=monSuperCodeIncrackablePlusLongCarApparementLeSecretPrecedentEtaitTropCourt
app.jwt-expiration-milliseconds=3600000
